### PR TITLE
Row Refactoring with Consumer and perf improvement

### PR DESCRIPTION
**Pull request by AllenFang**
- [x] Refactoring Selection Consumer
- [x] Refactoring Expand Consumer
- [x] Refactoring CellEdit Consumer
- [x] Enhance Row performance

### CODE REVIEW

**Comment by AllenFang** [comment]
https://github.com/react-bootstrap-table/react-bootstrap-table2/pull/537

**Comment by AllenFang** [comment]
https://github.com/react-bootstrap-table/react-bootstrap-table2/issues/559

**Comment by Philin-Anton** [comment]
How long do we need wait, that you merge the git branch?

**Comment by AllenFang** [comment]
@Philin-Anton  This week, all the tests is done. Sorry for lately fixed.  Quite busy.

**Pull request merged**
