### PR TITLE
Feat/cell editor

### PR DESCRIPTION
**Pull request by AllenFang**
#60

Big PR

### CODE REVIEW

**Comment by AllenFang** [comment]
@Chun-MingChen 

I think you forgot update the `.travis.yml`? in https://github.com/react-bootstrap-table/react-bootstrap-table2/pull/53 ?

Because this PR, I add `jsdom` and `jsdom-global` but still built fail on travis > https://travis-ci.org/react-bootstrap-table/react-bootstrap-table2/builds/276516432

You can trigger above job manually.

If yes, I'll update the travis config, thanks

**Comment by Chun-MingChen** [comment]
@AllenFang 

These are document from `yarn install --help`
```
--pure-lockfile                    don't generate a lockfile
--frozen-lockfile                  don't generate a lockfile and fail if an update is needed
```
Sorry for my careless, we do update `.travis.yml` with ` --pure-lockfile` and it will fix this issue.

**Comment by Chun-MingChen** [comment]
Besides, There's one more thing that we've set `postinstall` to run `lerna bootstrap` automatically. However, it's unnecessary for `CI` mode. I fix this issue in my next PR to set new CLI command for travis needs.

**Comment by AllenFang** [comment]
I'm already use npm as default in `travis.yml` in this PR, but you can change it in your PR

**Comment by Chun-MingChen** [comment]
Sure 💯

**Pull request merged**
