### PR TITLE
Various text and code fixes

### PR DESCRIPTION
**Pull request by FrancescoGd**
Fixed some typos, reworded some phrases and corrected a couple lines in example code

### CODE REVIEW

**Comment by AllenFang** [comment]
@FrancescoGd hi, I change your base to `develop` but please rebase your branch, thanks!

**Comment by FrancescoGd** [comment]
Yes, sorry, I thought that would be applicable just to code contributions and not to documentaion too... not a problem :)

Regards,
F.

**Comment by AllenFang** [comment]
thanks your contribution @FrancescoGd

**Comment by FrancescoGd** [comment]
Thank you @AllenFang for accepting it even though I messed with branching :D

**Pull request merged**
