### PR TITLE
[WIP] Add table footer

### LINKED ISSUE #2: Summary row or custom footer
Hi! Cool, that you decide to make a 2nd version of this table component!

Not sure if it implemented in the last version of react-bootstrap-table, but it would be cool to have a summary row as the last row of the table. And(or) a custom footer component for a table. 

Thanks!

### PR DESCRIPTION
**Pull request by osiux**
Fix #2 

Trying to add a footer for the table, this is a early PR just to ask if I'm in the right track.

### CODE REVIEW

**Comment by jonathanborges** [comment]
Any dates? This will be great!

**Comment by isuruamantha** [comment]
@AllenFang Could you please review the PR and merge it so that we can start using it

**Comment by ShanikaEdiriweera** [comment]
@AllenFang waiting for the feature. Much appreciated if you can review soon. Thanks :+1:

**Comment by danielfelgar** [comment]
@AllenFang i'm waiting for review and merge this PR too.

**Comment by jonathanborges** [comment]
All I want is a line on the end of the table. That I can pass infos inside. Simple as that. I'm really looking forward to this feature, keep us informed, please, again, this will be awesome!

**Comment by AllenFang** [comment]
guys... sorry I got serious disease from last week... will try to back in this weekend.

**Comment by osiux** [comment]
@AllenFang take your time to get better :) i think functionality wise this is done, just need to finish tests (that are mostly the same as for header)

**Comment by AllenFang** [comment]
Thanks @osiux :)

**Comment by AllenFang** [comment]
https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2019/01/20/version-bump.html

release on `react-bootstrap-table-next@2.1.0`
check [these](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Footer&selectedStory=Simple%20Footer&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) examples

**Comment by AllenFang** [comment]
thanks @osiux again 👍

**Comment by jonathanborges** [comment]
Great job, you guys don't even know how this was important for our business.

**Comment by AllenFang** [comment]
😂

**Pull request merged**
