### PR TITLE
[BUGFIX] Fix issue with missing onChange prop for selection checkbox

### PR DESCRIPTION
**Pull request by jeznag**
Fixes https://github.com/react-bootstrap-table/react-bootstrap-table2/issues/363
I'm not sure if this is the right approach or how to test this. It seems like we should do a test to make sure that when you click on the checkbox, the onSelectAll method gets fired. I tried this but it's not possible to use enzyme `mount` right now due to this error: ```It looks like you called `mount()` without a global document being loaded.```

### CODE REVIEW

**Comment by AllenFang** [comment]
Hello @jeznag is this PR really can fix #363 ?  I think the issue is from the `selection-cell.js` instead of `selection-header-cell.js`

if you still want to patch it, i recommend you to following code in [here](https://github.com/react-bootstrap-table/react-bootstrap-table2/blob/master/packages/react-bootstrap-table2/src/row-selection/selection-cell.js#L72)
```js
onChange={ () => {} }
```

why no op, because we handle the selection on the root element.

**Comment by jeznag** [comment]
@AllenFang sorry for the delay. I think it's needed in both places because there's a checkbox component in both the header selection cell and the selection cell.

**Comment by AllenFang** [comment]
@jeznag thanks, will release in next sprint.

**Comment by AllenFang** [comment]
Thanks your contribution, check this for newest release: https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/

**Pull request merged**
