### PR TITLE
[WIP] Animate row expansion

### PR DESCRIPTION
**Pull request by YassienW**
#728 
There are currently 2 limitations:

- ~~Programmatic expand management isn't animated yet~~
- ~~The bottom and top padding inside the expansion have to be removed for a smooth animation, we can 
   either keep it this way and the user can add his own padding, or we can add an extra div inside the 
   animation div with the padding~~

### CODE REVIEW

**Comment by AllenFang** [comment]
So far so good, I will check out this branch to see the transition, thanks. Please tag me when you complete this feature 👍

**Comment by AllenFang** [comment]
BTW, @YassienW https://github.com/react-bootstrap-table/react-bootstrap-table2/issues/735

**Comment by YassienW** [comment]
@AllenFang It's done. Let me know if anything needs to be adjusted

**Comment by AllenFang** [comment]
@YassienW oh, sorry, I missed this PR, let me check and thank you for this contribution!!

**Comment by AllenFang** [comment]
@YassienW hello, I think this PR is amazing for me, however, I will make it configurable, so I change this PR's base to `react-bootstrap-table:feature/row-expand-animate` and I will work on it. :)

**Comment by elmoro666** [comment]
I would very much like to have the ability to switch of the animation. It is slow and the motion is not smooth. Let me know if I can help with this. I have no pr experience, but I am happy to have a go

**Pull request merged**
