### PR TITLE
Ability to add classes to the table wrapper

### PR DESCRIPTION
**Pull request by MikeSha**
Let's say I need to add a 'table-responsive' class or another custom class.

### CODE REVIEW

**Comment by AllenFang** [comment]
@MikeSha sorry for lately reply, I will check this asap, thanks your contribution

**Comment by AllenFang** [comment]
@MikeSha would you please change your target branch to `develop`?  thanks!

**Comment by MikeSha** [comment]
@AllenFang Sure!

Done!

**Comment by MikeSha** [comment]
@AllenFang Sure. I'll do that a little bit later.

**Comment by MikeSha** [comment]
@AllenFang I created a new PR https://github.com/react-bootstrap-table/react-bootstrap-table2/pull/325. This one could be closed.

**Pull request closed without merging**
