### PR TITLE
fix linebreak-style

### PR DESCRIPTION
**Pull request by khaninD**
I use windows and i have CRLF and i have problem with eslint linebreak-style option ... this option cancel of check CRLF or LF linebreak style ...

### CODE REVIEW

**Comment by AllenFang** [comment]
HI @khaninD I think you can try to add `.editorconfig` and the content can be

```
end_of_line = lf
```

Not sure if it is work on widows, but if it's work, please consider to use this solution also it's worthy to commit to code base. thanks

**Comment by khaninD** [comment]
@AllenFang , eslint show errors. 
image

If i added end_of_line = if to .editorconfig,, new files will be with LF style, but old files will be CRLF ...

**Comment by AllenFang** [comment]
> If i added end_of_line = if to .editorconfig,, new files will be with LF style, but old files will be CRLF ...

hmm... that's correctly, how about you delete the repo and clone again? or use `--fix` to fix the legacy CRLF files?

Anyway, I dont think disable the `linebreak-style` is gest solution, it will make our codebase without consistency line break, if above solution is not work for you, I think you can enforce the line breaking on widows with CRLF by:

`"linebreak-style": ["error", "windows"]`

This solution maybe more safety.

**Comment by AllenFang** [comment]
Close it due to no response

**Pull request closed without merging**
